development:
  adapter: sqlite3
  database: db/development.sqlite3

test:
  adapter: sqlite3
  database: db/test.sqlite3

production:
  url: <%= ENV['DATABASE_URL'] %>

garoon:
  adapter: sqlite3
  database: db/garoon.sqlite3
  # database: ~/garoon.sqlite3
